### ISSUE TITLE
静态资源统筹中心

### ISSUE THREAD

**Issue by saltbo** [saltbo/ideas#12]
## 起因
初创企业野蛮生长，未来死了也无所谓，一旦成长起来，初期的混乱将为以后带来极大的麻烦。

## 功能
- 域名统一管理
- 云存储统一管理
- CDN统一管理
- 支持多家云平台

**Comment by colinrs** [comment]
- 感兴趣，想详细了解

**Comment by saltbo** [comment]
这个项目只是有个初步的想法，具体我也没有想好。

大概就是在阿里云OSS、七牛之类的存储之上分装一层，基于这个中间层解决两个问题。一是如果需要更换云服务商，可以做到业务方无感知迁移。二是业务方统一对接该服务，避免资源管理混乱，后期各种麻烦问题

**Comment by colinrs** [comment]
- 了解了，多谢解答

**Comment by saltbo** [comment]
不客气，我也是刚开始做开源，没啥经验。等我把uptoc搞完，走一个完整的开源项目的流程再说
